server:
  port: 30001

# spring
spring:
  application:
    name: face-sign-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_face_sign_edu_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      auth: admin@123
#      timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true  # 开启驼峰命名
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MinIO 配置
#minio:
#  endpoint: http://localhost:9000      # MinIO服务地址
#  fileHost: http://localhost:9000      # 文件地址host
#  bucketName: face-images                     # 存储桶bucket名称
#  accessKey: minioadmin                         # 用户名
#  secretKey: minioadmin                     # 密码
#  imgSize: 1024                           # 图片大小限制，单位：m
#  fileSize: 1024                          # 文件大小限制，单位：m
