server:
  port: 30001

spring:
  application:
    name: face-sign-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_face_sign_edu_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000
  minio:                                      # MinIO 配置
    endpoint: http://localhost:9000           # MinIO服务地址
    bucketName: face-images                   # 存储桶bucket名称
    accessKey: minioadmin                     # 用户名
    secretKey: minioadmin                     # 密码
  servlet:
    multipart:
      max-file-size: 50MB                     # 单个文件的最大大小
      max-request-size: 100MB                 # 单次请求的最大大小，适用于多文件上传
  config:
    import: "classpath:baidu.properties"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  mapper-locations: classpath*:com/face/sign/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml

baidu:
  face:
    appId: ${baidu.face.appId}
    apiKey: ${baidu.face.apiKey}
    secretKey: ${baidu.face.secretKey}



